### ISSUE TITLE
method for refreshing the data

### ISSUE THREAD

**Issue by php19** [1rosehip/jplist#20]
Hello,
firstly thanks for this amazing plugin! I searched now for many hours but didnt find an answer to my question.
i have external filters (like selects,...) which send an ajax request to my php server. As response i get json data and i generate divs (the .list-item) from it and append it to the .list div. 
how can i destroy the instance of jplist or reload it, so that it recognizes the new data?
Thank you!

**Comment by clod986** [comment]
Hello,
I have a related problem which I believe can be solved only by reinstantiating jplist, but maybe you could tell me how to do it.

With my JSON response I change some checkboxes that previously were used by jplist (most of the times are identical). They are not working after their replacement, but everything else still does, text filters and pagination included.

Thank you

**Comment by clod986** [comment]
I solved it by making sure the code to replace is in place at the moment of refreshing.

**Comment by no81no** [comment]
I'm glad it's working for you now.
Also it's possible to use the following function:
https://jplist.com/documentation/js-settings#redraw-callback-function

**Comment by gzparker** [comment]
Hi, I have a question that i've been trying to figure out for 2 days.  I am getting new data and storing it into the js with your add api, however, how do i clear all the data out and start it fresh?  For example I understand the del api to delete a row, but instead of 1 row, i'd like to wipe the whole thing and then use the add api to add new data.  How can I wipe the data already stored?  Thanks

**Comment by gzparker** [comment]
anyone here?
